##*************DATABASE************
#--------------* H2 *--------------
spring.datasource.url=jdbc:h2:mem:${DB_NAME:testdb}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${USERNAME:sa}
spring.datasource.password=${PASSWORD:sa}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.h2.console.settings.trace=false
# server sharing
spring.h2.console.settings.web-allow-others=true
