spring.application.name=basicFramework

spring.profiles.active=${PROFILE}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=method

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
# server sharing
spring.h2.console.settings.web-allow-others=true

