spring.application.name=basicFramework
server.port=9090
#-------* profile active *-------
spring.profiles.active=${PROFILE:dev}
#-------* exception handling config *-------
exception-handling.language-response.supported-langs=fa,en
exception-handling.language-response.pattern-name-file-i18n=Error_**
#-------* exception handling dispatcherServlet config *-------
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
server.error.whitelabel.enabled=false
#-------* swagger config *-------
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=method
#-------* Connection Pool *-------
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
#----------* HIBERNATE *----------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.schema_update.unique_constraint_strategy=RECREATE_QUIETLY
spring.jpa.properties.hibernate.id.new_generator_mappings=true
#----------* SECURITY *----------
## default username and password for login
#spring.security.user.name=user
#spring.security.user.password=user
#------------* ELK *------------
#manager.elastic-search.is-enable=false
#manager.elastic-search.host=localhost
#manager.elastic-search.port=9200
#manager.elastic-search.connection-time-out=3000000
#manager.elastic-search.trace.input-request.isEnable=true
#manager.elastic-search.trace.third-party.isEnable=true

manager.exception-handling.is-enable = true
manager.exception-handling.type=PROPERTIES_FILE
manager.exception-handling.supportedLangs=fa,en


