#spring.main.banner-mode=off
spring.application.name=mehdi-hosseini-basicFramework
server.port=7676
server.servlet.context-path=/mehdi-hosseini
##************SWAGGER**************
springdoc.api-docs.path=/swagger
springdoc.swagger-ui.path=/swagger.html
springdoc.swagger-ui.operationsSorter=method
##************VAADIN***************
vaadin.urlMapping=/app/*
#vaadin.launch-browser=true
vaadin.productionMode=false
##**********DATABASE-H2************
spring.datasource.url=jdbc:h2:mem:mehdiHosseini
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=mh
spring.datasource.password=mh
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
spring.h2.console.path=/h2
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false